Update rom.yml

diff --git a/.github/workflows/rom.yml b/.github/workflows/rom.yml
--- a/.github/workflows/rom.yml
+++ b/.github/workflows/rom.yml
@@ -1,101 +1,79 @@
 name: Build RisignOSS
 permissions:
-  contents: write
   actions: write
+  contents: write
+  statuses: write
   
 on:
   workflow_dispatch:
   
 jobs:
-  Read-configuration:
-    name: 🐂 Parse config
-    runs-on: ubuntu-latest
-    outputs:
-      BUILD_DATE: ${{ steps.generate-builddate.outputs.BUILDDATE }}
-    steps:
-      # This action checks-out your CONFIGSitory under $GITHUB_WORKSPACE, so your workflow can access it.
-      - name: 😄 Checkout
-        uses: actions/checkout@v4
-
-      # Set compile time.
-      - name: ⏰ Set builddate
-        id: generate-builddate
-        run: echo "BUILDDATE=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
-
-  Build-Kernel:
+  Build-rom:
     name: "🐎 Build Rom"
     runs-on: fast
-    needs:
-      - Read-configuration
-    strategy:
-      fail-fast: false
-    env:
-      # Basic configuration
-      BUILD_DATE: "${{ needs.Read-configuration.outputs.BUILD_DATE }}"
       
     steps:
-      # This action checks-out your CONFIGSitory under $GITHUB_WORKSPACE, so your workflow can access it.
-      - name: 😄 Checkout
-        uses: actions/checkout@v4
-      
       - name: Set Swap Space
         uses: pierotofy/set-swap-space@master
         with:
-          swap-size-gb: 12
+          swap-size-gb: 16
+
+      - name: ⏰ Set builddate
+        id: generate-builddate
+        run: echo "BUILDDATE=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
         
-      - name: Set CONFIG Environment Variable
-        run: |
-          CURRENT_DIR=$(pwd)
-          echo "CURRENT_DIR=$CURRENT_DIR" >> $GITHUB_ENV
+      # This action checks-out your CONFIGSitory under $GITHUB_WORKSPACE, so your workflow can access it.
+      - name: 😄 Checkout
+        uses: actions/checkout@v4
           
       # Install prerequisites for Ubuntu
       - name: ⭐ Install prerequisites
         run: |
-          cd "$CURRENT_DIR"
-          sudo apt update
-          DEBIAN_FRONTEND=noninteractive sudo apt install -yq bc bison lib32ncurses5-dev libncurses5 libncurses5-dev build-essential openvpn openvpn-systemd-resolved ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
-          mkdir -p ./git-repo
-          echo "Downloading repo tool..."
-          curl https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
-          chmod a+rx ./git-repo/repo
-          echo "REPO=$CURRENT_DIR/./git-repo/repo" >> $GITHUB_ENV
+          sudo apt update && sudo apt -y upgeade
+          DEBIAN_FRONTEND=noninteractive sudo apt install -y \
+          bc bison lib32ncurses5-dev libncurses5 libncurses5-dev build-essential \
+          openvpn openvpn-systemd-resolved ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf \
+          imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 \
+          libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc \
+          zip zlib1g-dev
 
-      - name: Connect to VPN
-        uses: "kota65535/github-openvpn-connect-action@v2"
-        with:
-          config_file: .github/workflows/client2.ovpn
-          username: ${{ secrets.OVPN_USERNAME }}
-          password: ${{ secrets.OVPN_PASSWORD }}
+      - name: Configure the 'repo' environment
+        run: |
+          # Check if repo is already installed
+          if ! command -v repo >/dev/null 2>&1; then
+            echo "Repo not found. Installing now..."
+            # Create bin directory if it doesn't exist
+            mkdir -p ~/bin
+            # Download repo script
+            curl https://storage.googleapis.com/git-repo-downloads/repo >> ~/bin/repo
+            # Make repo script executable
+            chmod a+x ~/bin/repo
+            # Create symbolic link to /usr/bin/repo
+            sudo ln -sf "/home/$(whoami)/bin/repo" "/usr/bin/repo"
+            echo "Repo installation complete."
+          else
+            echo "Repo already installed."
+          fi
+        continue-on-error: true
           
       - name: 🌟 checkout aosp build system
         run: |
-          cd "$CURRENT_DIR"
-          mkdir -p rom
-          cd rom
-          git lfs install
-          $REPO init -u https://github.com/RisingOS-Revived/android -b qpr2 --git-lfs --depth=1
+          repo init -u https://github.com/RisingOS-Revived/android -b qpr2 --git-lfs --depth=1
           git clone --depth=1 https://github.com/Ecolifyt/local_manifests .repo/local_manifests
           find .repo -name '*.lock' -delete
-          $REPO sync -c -j12 --force-sync --no-clone-bundle --no-tags --prune
-      # KSU specific steps
+          repo sync -c -j32 --force-sync --no-clone-bundle --no-tags --prune
+     
       - name: 💫 Build Rom
         run: |
-          set -x
-          set -e
-          cd "$CURRENT_DIR/rom"
-          source build/envsetup.sh
-          riseup cheetah eng && rise b
+          bash build.sh
       
       - name: "💾 Upload RisignOSS build files => (${{ env.BUILD_DATE }})"
-        env:
-          ANYKERNEL3_FILE: "android14-6.1-susfsnext-${{ env.BUILD_DATE }}"
         continue-on-error: true
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ env.ANYKERNEL3_FILE }}
           path: |
-            ${{ env.CURRENT_DIR }}/rom/out/target/product/cheetah/*.zip
-            ${{ env.CURRENT_DIR }}/rom/out/target/product/cheetah/*.img
+            rom/out/target/product/cheetah/*.zip
+            rom/out/target/product/cheetah/*.img
 
       - name: 🧧 Create GitHub Release => (${{ env.BUILD_DATE }})
         env:
@@ -112,6 +90,6 @@ jobs:
         with:
           tag_name: v${{ env.BUILD_DATE }}.${{ github.run_number }}
           files: |
-             ${{ env.CURRENT_DIR }}/rom/out/target/product/cheetah/*.zip
-             ${{ env.CURRENT_DIR }}/rom/out/target/product/cheetah/*.img
+             out/target/product/cheetah/*.zip
+             out/target/product/cheetah/*.img
           generate_release_notes: true
